# Stolen from finite
[package]
name = "scholar"
version = "0.0.3"
entrypoint = "src/scholar.typ"
authors = ["Siddharth Narayan"]
license = "MIT"
description = "Build a beautiful assignment"
repository = "https://github.com/siddharth-narayn/scholar"
keywords = []
categories = []
disciplines = []
compiler = "0.13.0"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	"assets",
	".typstignore",
	"Justfile",
]
